### ISSUE TITLE
Support Bugsnag

### ISSUE THREAD

**Issue by GrahamCampbell** [webplates/nofw#2]

**Comment by sagikazarmark** [comment]
Thanks for the suggestion. Do you mean instead of Airbrake/Errbit or as an additional option? I imagined nofw as more of a skeleton application, so I would like to avoid usual configuration and rather suggest cloning and modifying nofw. That said, I can imagine multiple example configuration in the repo.

**Comment by GrahamCampbell** [comment]
Yes, or just replace them. I think the original framework supported Bugsnag. :)

**Comment by sagikazarmark** [comment]
Thinking about how this could work. I feel that sticking to one error reporting service might not be the right choice (this applies to the current errbit/airbrake too). I am thinking about maintaining a wiki which could contain instructions for setting up different services.

Currently the following services are on my list:

- Airbrake/Errbit
- Newrelic
- Bugsnag
- Sentry
- Rollbar

Nofw would not have support for them OOTB, but it would be quite easy to set them up following the instructions in the wiki.

What do you think?
